[package]
name = "test_import_maps"
version = "0.1.0"
description = "Test import maps"
author = ""
license = "MIT"

[dependencies]

[dev-dependencies]

[build]
src = "src"
target = "browser"
module = "esm"
out = "dist"

[targets.browser]
tree_shaking = true
dev = false

[targets.browser.import_map]
react = "https://esm.sh/react@18"
lodash = "https://cdn.skypack.dev/lodash"