[package]
name = "test-missing-main"
version = "0.1.0"
description = "Test missing main function"
author = ""
license = "MIT"

[dependencies]

[dev-dependencies]

[build]
src = "src"
out = "dist"
target = ""
module = "esm"